// Generated by view binder compiler. Do not edit!
package com.example.bikerentalsystem.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.bikerentalsystem.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnPromotions;

  @NonNull
  public final Button btnRentalHistory;

  @NonNull
  public final Button btnReserve;

  @NonNull
  public final TextView tvWelcome;

  private ActivityMainBinding(@NonNull LinearLayout rootView, @NonNull Button btnPromotions,
      @NonNull Button btnRentalHistory, @NonNull Button btnReserve, @NonNull TextView tvWelcome) {
    this.rootView = rootView;
    this.btnPromotions = btnPromotions;
    this.btnRentalHistory = btnRentalHistory;
    this.btnReserve = btnReserve;
    this.tvWelcome = tvWelcome;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnPromotions;
      Button btnPromotions = ViewBindings.findChildViewById(rootView, id);
      if (btnPromotions == null) {
        break missingId;
      }

      id = R.id.btnRentalHistory;
      Button btnRentalHistory = ViewBindings.findChildViewById(rootView, id);
      if (btnRentalHistory == null) {
        break missingId;
      }

      id = R.id.btnReserve;
      Button btnReserve = ViewBindings.findChildViewById(rootView, id);
      if (btnReserve == null) {
        break missingId;
      }

      id = R.id.tvWelcome;
      TextView tvWelcome = ViewBindings.findChildViewById(rootView, id);
      if (tvWelcome == null) {
        break missingId;
      }

      return new ActivityMainBinding((LinearLayout) rootView, btnPromotions, btnRentalHistory,
          btnReserve, tvWelcome);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
