// Generated by view binder compiler. Do not edit!
package com.example.bikerentalsystem.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.bikerentalsystem.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPromotionsBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView tvDiscount;

  @NonNull
  public final TextView tvPromotionDescription;

  @NonNull
  public final TextView tvPromotionName;

  private ActivityPromotionsBinding(@NonNull LinearLayout rootView, @NonNull TextView tvDiscount,
      @NonNull TextView tvPromotionDescription, @NonNull TextView tvPromotionName) {
    this.rootView = rootView;
    this.tvDiscount = tvDiscount;
    this.tvPromotionDescription = tvPromotionDescription;
    this.tvPromotionName = tvPromotionName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPromotionsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPromotionsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_promotions, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPromotionsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.tvDiscount;
      TextView tvDiscount = ViewBindings.findChildViewById(rootView, id);
      if (tvDiscount == null) {
        break missingId;
      }

      id = R.id.tvPromotionDescription;
      TextView tvPromotionDescription = ViewBindings.findChildViewById(rootView, id);
      if (tvPromotionDescription == null) {
        break missingId;
      }

      id = R.id.tvPromotionName;
      TextView tvPromotionName = ViewBindings.findChildViewById(rootView, id);
      if (tvPromotionName == null) {
        break missingId;
      }

      return new ActivityPromotionsBinding((LinearLayout) rootView, tvDiscount,
          tvPromotionDescription, tvPromotionName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
