// Generated by view binder compiler. Do not edit!
package com.example.bikerentalsystem.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.bikerentalsystem.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnRegister;

  @NonNull
  public final EditText etEmailRegister;

  @NonNull
  public final EditText etName;

  @NonNull
  public final EditText etPasswordRegister;

  @NonNull
  public final EditText etPaymentInfo;

  @NonNull
  public final TextView tvRegisterTitle;

  private ActivityRegisterBinding(@NonNull ScrollView rootView, @NonNull Button btnRegister,
      @NonNull EditText etEmailRegister, @NonNull EditText etName,
      @NonNull EditText etPasswordRegister, @NonNull EditText etPaymentInfo,
      @NonNull TextView tvRegisterTitle) {
    this.rootView = rootView;
    this.btnRegister = btnRegister;
    this.etEmailRegister = etEmailRegister;
    this.etName = etName;
    this.etPasswordRegister = etPasswordRegister;
    this.etPaymentInfo = etPaymentInfo;
    this.tvRegisterTitle = tvRegisterTitle;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnRegister;
      Button btnRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnRegister == null) {
        break missingId;
      }

      id = R.id.etEmailRegister;
      EditText etEmailRegister = ViewBindings.findChildViewById(rootView, id);
      if (etEmailRegister == null) {
        break missingId;
      }

      id = R.id.etName;
      EditText etName = ViewBindings.findChildViewById(rootView, id);
      if (etName == null) {
        break missingId;
      }

      id = R.id.etPasswordRegister;
      EditText etPasswordRegister = ViewBindings.findChildViewById(rootView, id);
      if (etPasswordRegister == null) {
        break missingId;
      }

      id = R.id.etPaymentInfo;
      EditText etPaymentInfo = ViewBindings.findChildViewById(rootView, id);
      if (etPaymentInfo == null) {
        break missingId;
      }

      id = R.id.tvRegisterTitle;
      TextView tvRegisterTitle = ViewBindings.findChildViewById(rootView, id);
      if (tvRegisterTitle == null) {
        break missingId;
      }

      return new ActivityRegisterBinding((ScrollView) rootView, btnRegister, etEmailRegister,
          etName, etPasswordRegister, etPaymentInfo, tvRegisterTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
