// Generated by view binder compiler. Do not edit!
package com.example.bikerentalsystem.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.bikerentalsystem.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityReservationBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnEndRental;

  @NonNull
  public final Button btnStartRental;

  private ActivityReservationBinding(@NonNull LinearLayout rootView, @NonNull Button btnEndRental,
      @NonNull Button btnStartRental) {
    this.rootView = rootView;
    this.btnEndRental = btnEndRental;
    this.btnStartRental = btnStartRental;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityReservationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityReservationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_reservation, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityReservationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnEndRental;
      Button btnEndRental = ViewBindings.findChildViewById(rootView, id);
      if (btnEndRental == null) {
        break missingId;
      }

      id = R.id.btnStartRental;
      Button btnStartRental = ViewBindings.findChildViewById(rootView, id);
      if (btnStartRental == null) {
        break missingId;
      }

      return new ActivityReservationBinding((LinearLayout) rootView, btnEndRental, btnStartRental);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
